name: Fly Deploy and Tag

on:
  push:
    branches:
      - main  # mainブランチにpushされたら実行

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          # git pushするためにトークンが必要
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: superfly/flyctl-actions/setup-flyctl@master

      # 【ここから修正】
      # flyctl secrets set のステップを削除

      # 手順2: Fly.ioへデプロイする (--envフラグは削除)
      - name: Deploy to Fly
        run: flyctl deploy --remote-only --app hisameai-mark-4
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      # 【ここまで修正】

      # Gitのユーザー情報を設定
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      # デプロイ成功のタグを作成してPush
      - name: Create and Push Deploy Tag
        run: |
          TIMESTAMP=$(date -u +%Y%m%d-%H%M%S)
          git tag deploy-${TIMESTAMP}
          git push origin --tags