name: Fly Deploy and Tag

on:
  push:
    branches:
      - main  # mainブランチにpushされたら実行

jobs:
  deploy:
    name: Deploy app and Push Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # git pushするためにトークンが必要
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: superfly/flyctl-actions/setup-flyctl@master

      # Fly.ioへデプロイ
      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      # Gitのユーザー情報を設定
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      # デプロイ成功のタグを作成してPush
      - name: Create and Push Deploy Tag
        run: |
          TIMESTAMP=$(date -u +%Y%m%d-%H%M%S)
          git tag deploy-${TIMESTAMP}
          git push origin --tags